[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
linea = "https://rpc.sepolia.linea.build"

[etherscan]
linea = { key = "${LINEASCAN_API}", url = "https://api-sepolia.lineascan.build/api", chain=59141 }
